### ISSUE TITLE
Converting txt file to doc

### ISSUE THREAD

**Issue by matheohan** [dwaaan/HRConvert2-Docker#13]
Hi, 

First of all thanks for your amazing project.
Though i encounter an issue, when i want to convert a txt file to a doc file i got the following error when saving the file : 
" Error, file not found"

Here is my docker compose in portainer : 

```
version: "3"
services:
  app:
    image: dwaaan/hrconvert2-docker:latest
    restart: always
    container_name: hrconvert
    network_mode: main
    volumes:
      - /home/DIKING/hrconvert/config.php:/var/www/html/HRProprietary/HRConvert2/config.php

```

I didn't change anything to the configuration and i run it behind a reverse proxy (nginx)
I notice in the log that i have this message : 
"AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.23. Set the 'ServerName' directive globally to suppress this message"

Thanks for any help, and sorry in advance if im not clear ( im kinda new to self hosted world )
